### ISSUE TITLE
一批链接需要更新

### ISSUE THREAD

**Issue by run-ze** [wzhudev/redi-site#3]
比如 [/pages/index.zh-CN.mdx](https://github.com/hullis/redi-site/blob/main/pages/index.zh-CN.mdx) 开头的博客链接是 /blog/，但是你的博客已经变成了 /blogs/；
还有 [/pages/blogs/di.zh-CN.mdx](https://github.com/hullis/redi-site/blob/main/pages/blogs/di.zh-CN.mdx) 末尾的 Gist 链接，因为用户名改变，所以也需要更新。

刚看到这里，所以只发现两个，实际上可能不止这些。

**Comment by wzhudev** [comment]
谢谢！欢迎 PR

**Comment by wzhudev** [comment]
Hi @run-ze . 官网的链接已经更新，谢谢你的指正。
